#SanaliEnviroment
STAGING = 'https://ai-staging.salina.app/login'
PRODUCTION = 'https://ai.salina.app/login'

#UserCredentials
USERNAME = 'mediameterinctesting@gmail.com'
PASSWORD = 'Cool9319*'

#QUICKY_WAIT
QUICK_WAIT = 5
MIDDLE_WAIT = 10

#AISearchWaitingTime
AI_INQUIRY_WAITING_TIME_RESPONSE = 80
SALINA_INQUIRY_WAITING_TIME_RESPONSE = 40
SALINA_INQUIRY_WAITING_TIME_FOR_FILE_DOCUMENT = 50
SALINA_INQUIRY_WAITING_TIME_FOR_VIDEOS_FILES_UPLOAD = 50

#GLOBAL_TIME_WAT
GLOBAL_TIME_WAIT = 10000

#GENERATE_IMAGE_WAITING_TIME
GENERATE_IMAGE_WAIT = 40

#WAITING_TIME_FOR_FILES_UPLOAD_AND_ATTACHMENT
WAITING_TIME_FOR_NORMAL_FILE_DOCUMENT_UPLOAD = 60
WAITING_TIME_FOR_VIDEOS_FILES_UPLOAD = 60
WAITING_TIME_FOR_FILE_ATTACHMENT = 60

#WAITING_TIME_FOR_HUGE_FILES_UPLOAD_AND_ATTACHMENT
WAITING_TIME_FOR_HUGE_VIDEOS_FILES_UPLOAD = 180
WAITING_TIME_FOR_HUGE_NORMAL_FILE_DOCUMENT_UPLOAD = 180
WAITING_TIME_FOR_HUGE_NORMAL_FILE_DOCUMENT_ATTACHMENT = 180

#WAITING_TIME_FOR_VIDEO_PLAYER_PLAY
VIDEO_PLAYER_PLAYING_TIME = 120

#SMALL_WAITING_TIME_FOR_TRANSCRIPT_SEGMENT_DISPLAYED
SMALL_TRANSCRIPT_SEGMENT_DISPLAYED_WAITING_TIME = 120

#WAITING_TIME_FOR_TRANSCRIPT_SEGMENT_DISPLAYED
TRANSCRIPT_SEGMENT_DISPLAYED_WAITING_TIME = 180


#AISearchFiles
AI_SEARCH_DOCUMENTS_ATTACHMENT =  "C:\\Users\\Jerome\\Desktop\\BEBOT\\cognitive-neuroscience-of-video-games.pdf"

#FilesUpload
NORMAL_FILE_UPLOAD = "C:\\Users\\Jerome\\Desktop\\BEBOT\\tsla-10k_20201231-gen.pdf"
NORMAL_FILE_UPLOAD_ATTACHMENT = "C:\\Users\\Jerome\\Desktop\\BEBOT\\extended definition example what is love.pdf"

#VdeosFileUpload
VIDEOS_FILES_UPLOAD = "C:\\Users\\Jerome\\Desktop\\Benchmarking\\How To Build Generative AI Models Like OpenAI's Sora - 34.05.mp4"